### ISSUE TITLE
Pull requests here won’t count toward Hacktoberfest.

### ISSUE THREAD

**Issue by hacktoberfest-team** [s-bridges/Hacktoberfest_Fizzbuzz#44]
Hi there,

Thanks for your interest in Hacktoberfest and helping others learn how to make their first contributions to open source!

That said, high-quality contributions are part of the [the core values of Hacktoberfest](https://hacktoberfest.digitalocean.com/details), so we kindly ask that you do not create repositories which allow users to quickly gain a PR toward completing the challenge.

We encourage you to take a look at our list of [Hacktoberfest issues](https://hacktoberfest.digitalocean.com/#projects) for inspiration and ideas about making meaningful contributions to open source projects.

_Due to this, we've added this repository to our list of excluded repositories and pull requests here will not count toward Hacktoberfest 2019._

Please note, you are welcome to keep running this repository as a learning tool for new contributors to open-source, but pull requests won’t count toward Hacktoberfest.

Happy Hacking,
The Hacktoberfest Team

Hacktoberfest is presented by [DigitalOcean](https://do.co/hacktoberfest50) and [DEV](https://dev.to).

**Comment by swingcake** [comment]
This one particularly wasn't that "low-effort" repo imo. Was fun to contribute anyway.

**Comment by s-bridges** [comment]
Yeah I don’t really see it as “spam” either. I think shutting down repos that allow developers that might not be at a steady open source level just makes it so digitalocean can back out of a value they once held. I was proud to participate back then, proud to show people how to use github, how to contribute to open source, how to better themselves as a developer. Seems these values we all once shared have changed, too bad. I’ll be ending my two 64gb droplets for sure because it just seems they are targeting me at this point. Thank you everyone for contributing. Fizz buzz is a popular challenge that is still used in interviews, it is a great way to show hiring managers you know how to apply the logic and skill you’ve learned. Even if this repo never gets another PR, I hope everyone that has contributed continues to develop their skills and push themselves to be the best developer they can. Don’t do it for a shirt, do it for the future. Much love contributors. #stillwontmakemyprivaterepospublic

**Comment by hacktoberfest-team** [comment]
@s-bridges You are welcome to keep running this repository as a learning tool for new contributors to open-source, however, pull requests won’t count toward Hacktoberfest as this repository doesn't align with our shared values for the competition. If you have further questions, please reach out to us at hacktoberfest at digitalocean dot com

**Comment by s-bridges** [comment]
> @s-bridges You are welcome to keep running this repository as a learning tool for new contributors to open-source, however, pull requests won’t count toward Hacktoberfest as this repository doesn't align with our shared values for the competition. If you have further questions, please reach out to us at hacktoberfest at digitalocean dot com

Does this not constitute spam itself? I am very well aware that I am allowed to run any repository that I create as they are mine. DigitalOcean, nor any organization doing business on their behalf own any rights to any of my repositories, nor are you granted the permission to tell me to delete a repository. I appreciate the sweet gesture though. If you are interested in discussing this further, I can send an invoice for my time.
